### ISSUE TITLE
icebreaker - no BIOS on serial

### ISSUE THREAD

**Issue by biot** [litex-hub/litex-boards#105]
When I follow the instructions on https://github.com/enjoy-digital/litex (point 4 is missing BTW) I don't get the BIOS output on serial as shown in point 5.

using `icebreaker.py --build` builds fine without errors, using `--load` also works fine but does nothing, and using `--flash` looks like it flashes the icebreaker, but still no serial output. However in that case the board does a slow LED flashing, alternating between green and red LEDs.

I have verified with iceprog that the bios.bin and icebreaker.bin as built match what's in the flash after `--flash`.

Can you confirm I didn't miss anything? Maybe flesh out point 4 in the docs?

**Comment by enjoy-digital** [comment]
Thanks @biot for reporting. It seems the execution of the BIOS from SPI Flash was broken. I updated the target and fixed that, could you do a test with latest LiteX/LiteX-boards? `./icebreaker.py --cpu-type=serv --build --flash`

**Comment by biot** [comment]
Yes, that's fixed it, thanks very much!

Incidentally with the "serv" CPU core I get:
   BIOS CRC failed (expected 000000000000000000, got 0000000000000000g0)
   The system will continue, but expect problems.

...but all is well with vexriscv.
