### ISSUE TITLE
Generated C code fails to compile when no uart is enabled

### ISSUE THREAD

**Issue by hansfbaier** [litex-hub/litex-boards#147]
For example in the sds1104xe board, which has no uart,
the generated code fails to compile, because still
some IRQ related code is generated, but without the
definitions in the header.
This issue also is relevant for other boards,
when uart is being disabled.

**Comment by enjoy-digital** [comment]
Thanks, this is fixed with https://github.com/enjoy-digital/litex/commit/1ce194007b684086dcf6af000fce946e36ffc445.
