### ISSUE TITLE
Import mechanism in litex_boards.target hides errors in imported files

### ISSUE THREAD

**Issue by mwelling** [litex-hub/litex-boards#22]
The bare except at https://github.com/litex-hub/litex-boards/blob/2a0fbcadd224ad102463c4c0b04f2bd8b3c74407/litex_boards/targets.py#L11 means that if your `target.py` file has any errors in it, you will get a weird error about the file not existing.

Really you should just be catching `ModuleNotFound` exceptions. See patch below;
```patch
diff --git a/litex_boards/targets.py b/litex_boards/targets.py
index 8ae7041..293e35b 100644
--- a/litex_boards/targets.py
+++ b/litex_boards/targets.py
@@ -8,7 +8,7 @@ class Targets:
         for support in ["official", "partner", "community"]:
             try:
                 return importlib.import_module("litex_boards." + support + ".targets." + name)
-            except:
+            except ModuleNotFoundError:
                 pass
         raise ModuleNotFoundError
 
```

If you have an error in your target file now, you get an exception like you expected.

**Comment by enjoy-digital** [comment]
Thanks! i was aware of the issue but not of how to fix it easily :) It's implemented with https://github.com/litex-hub/litex-boards/commit/4231d599012a46d9fe3198364376cac4418cbe76.
