### ISSUE TITLE
iCEbreaker SPRAM size inconsistency.

### ISSUE THREAD

**Issue by JosephBushagour** [litex-hub/litex-boards#246]
The SPRAM size on the iCEbreaker seems to be half of what is available in the specs and also disagrees with the comment above it (the comment says 128kB whereas the code uses 64kB). 
https://github.com/litex-hub/litex-boards/blob/a3f479837c0950d7f33f6a9e7bc582eef28c01b2/litex_boards/targets/1bitsquared_icebreaker.py#L94-L96

I traced this inconsistency back to this commit, which seems to be related to DVI video: https://github.com/litex-hub/litex-boards/commit/7e3b8ab3b52dc33e8897cbf908d1470bf226c14b

Was this a mistake or is there some reason the SPRAM was decreased to 64kB? I personally haven't noticed issues when I change it to 128kB locally.

**Comment by enjoy-digital** [comment]
Thanks @JosephBushagour, this was probably a mistake and shouldn't have been included in the commit (I probably this this to free up a SPRAM while testing but don't remember the reason). This is reverted with https://github.com/litex-hub/litex-boards/commit/10bfd50e22c73bf679525fbfbe602340e9d5a999.

**Comment by JosephBushagour** [comment]
Thanks!
