### ISSUE TITLE
            uart_name="jtag_atlantic", # not working any more?

### ISSUE THREAD

**Issue by AnttiLukats** [litex-hub/litex-boards#27]
uart_name="jtag_atlantic",

it used to work, but now throws duplicate name error, any new syntax needed?

TypeError: __init__() got multiple values for keyword argument 'uart_name'

**Comment by enjoy-digital** [comment]
In fact you now just need to pass it as an argument when executing your target, ex for the de0nano:
`./de0nano.py --uart-name=jtag_atlantic`

**Comment by AnttiLukats** [comment]
I see ;) was not obvious..

**Comment by enjoy-digital** [comment]
Indeed sorry, you can use `--help` on your target to list the available arguments.
