### ISSUE TITLE
orangecrab doesn't build

### ISSUE THREAD

**Issue by mikey** [litex-hub/litex-boards#274]
If I do:
```
cd litex_boards/targets
./gsd_orangecrab.py --build
```
It runs for a while but eventually dies in yosys with:
```
4.35.9. Executing OPT_CLEAN pass (remove unused cells and wires).
Finding unused cells or wires in module \gsd_orangecrab..
ERROR: Conflicting init values for signal 1'0 (\basesoc_cdcusb_cdcusbphy_inhandler_dtbs [4] = 1'0 != 1'x).
```
I assume this is an issue with valenty usb, but building valenty outside of litex isn't something I understand.

**Comment by tcal-x** [comment]
I think this is an issue in Yosys that was resolved a few weeks ago.   Can you try a more recent Yosys?

https://github.com/YosysHQ/yosys/issues/2926

**Comment by mikey** [comment]
Yep, that was the problem. Updating yosys fixed it. Thanks. @tcal-x
