### ISSUE TITLE
Butterstick: Use 2Gb DDR3 as default instead of 8Gb.

### ISSUE THREAD

**Issue by enjoy-digital** [litex-hub/litex-boards#298]
"We have to inform you however that despite advertising a full gigabyte of DDR3 memory, the hardware in fact only has 2 gigabits of DDR3."

**Comment by tpwrules** [comment]
As a temporary workaround, replacing MT41K256M16 with MT41K64M16 in https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/gsd_butterstick.py seems to work fine.

**Comment by enjoy-digital** [comment]
With https://github.com/litex-hub/litex-boards/pull/299, 2Gb is now the default on Butterstick and 8Gb can be selected with `--sdram-device=MT41K512M16`.
