### ISSUE TITLE
Error in connector mapping for Colorlight 5A-75E V6.0

### ISSUE THREAD

**Issue by WhichWayWazzit** [litex-hub/litex-boards#362]
Hello! 

It looks as though there's a typo in connector mapping https://github.com/litex-hub/litex-boards/blob/master/litex_boards/platforms/colorlight_5a_75e.py#L216

`("j16", "F14 G13 F12 - F13 F14 E14 N4 N5 N3 P3 P4 M3 N1 M4 -"),`

The first pin (index J16:0) is actually G14 and _not_ F14, which you see repeated later(J16:5) which is correct.

I've actually tested this with a pinscan of a 5A-75E V8 but have found the v6 mappings to fully match up so would assume that there is the same error in V6.

**Comment by enjoy-digital** [comment]
Thanks @WhichWayWazzit! I just integrated your suggestion fix with https://github.com/litex-hub/litex-boards/commit/37783ff9fd8dcab9c120f8018e901682759f1616.
