### ISSUE TITLE
antmicro_lpddr4_test_board.py has incorrect import

### ISSUE THREAD

**Issue by aaronachang** [litex-hub/litex-boards#387]
antmicro_lpddr4_test_board.py imports lpddr4_test_board from platforms, but it should be antmicro_lpddr4_test_board.

Seems like it was missed in this commit: https://github.com/litex-hub/litex-boards/commit/03accabc257ca06dd608db06bde8d0100c1e68de

**Comment by enjoy-digital** [comment]
Thanks, this is fixed with https://github.com/litex-hub/litex-boards/commit/e38bad22e3b7328807384646920d8e55d08179a8.
