### ISSUE TITLE
Cannot Compile Test for Tang Nano 9k

### ISSUE THREAD

**Issue by Chandler-Kluser** [litex-hub/litex-boards#413]
I get this error when compiling the test sample for Sipeed Tang Nano 9k with GoWin Educational IDE v1.9.8.03:

```
python3 -m litex_boards.targets.sipeed_tang_nano_9k --with-video-terminal --build
```

![](https://i.ibb.co/Z66FK4V/image.png)

**Comment by enjoy-digital** [comment]
Thanks @Chandler-Kluser for the feedback. Not sure the build has been tested before with Video on the Tang Nano 9K, I just fixed it with https://github.com/litex-hub/litex-boards/commit/8c3a5c0608148a5399447f0a72621f3caf630db7 which should make it similar to Tang Nano 4K.
