### ISSUE TITLE
CSR_SCRATCH with arty buttons

### ISSUE THREAD

**Issue by Kimplul** [litex-hub/litex-boards#426]
Hi, https://github.com/litex-hub/linux/blob/litex-rebase/drivers/soc/litex/litex_soc_ctrl.c#L23 seems to assume that `CSR_SCRATCH` is always at offset `0x4` from the CSR base, but the `digilent_arty` board after commit bf458e388efea428189a4a33c1cb40cadce85d48 places it at `0x804`, resulting in a kernel panic when testing https://github.com/litex-hub/linux-on-litex-rocket. Setting `with_buttons = False` places the scratch CSR at `0x4`.

**Comment by enjoy-digital** [comment]
Hi @Kimplul,

thanks for the feedback and fix suggestion. The CSR mapping is indeed dynamic and the issue you are facing is that Linux-on-LiteX-Rocket project uses a static .dts for now. I just set with_buttons default value to False with https://github.com/litex-hub/litex-boards/commit/9cd1c1cbd5c4be1d0a68c65254ac30890074419b which should fix the issue. In the future, we'll try to switch Linux-on-LiteX-Rocket to dynamic .dts (as we are doing on Linux-on-Litex-VexRiscv) to avoid this.
