### ISSUE TITLE
Sipeed Tang Nano 9k no Boot Message from SoC-Core 

### ISSUE THREAD

**Issue by maggo1404** [litex-hub/litex-boards#481]
Hi,

i Build with the Standard config the bitfile. 
`sipeed_tang_nano_9k.py —build` 

When finish load to the SRAM or Flash the bitfile.

The LEDs performe a running light Show. 
Open the serial Port with minicom (115200 8N1) and push the reset Button i hav never sean the boot Message from bios. 

When the build with `litex_sim —build` then see the boot Message. 

OS Lububtu 22.04 LTS

Regards maggo1404

**Comment by trabucayre** [comment]
Not fully sure but [rom is in spiflash](https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/sipeed_tang_nano_9k.py#L85)
Could you try with:
```
./sipeed_tang_nano_9k.py --prog-kit openfpgaloader --flash --build
```

**Comment by maggo1404** [comment]
is not sucessfull :(

i have the small idea the VM is not the perfect Environment for the programming a FPGA-board. 
![2023-03-12 17_37_21-VirtualBoxVM](https://user-images.githubusercontent.com/509301/224558850-8e1e899c-3de8-4edb-b5f1-f4e13255bd19.png)

have you the settings for the gowin programmer? I can try with the windows-versionen. I have search and havn't found the perfect setting. :(

**Comment by maggo1404** [comment]
reboot the FPGA-Board and PC and now running the soft-Core. 
![2023-03-12 17_54_50-COM54 - PuTTY](https://user-images.githubusercontent.com/509301/224560049-fc262628-ee24-4925-b408-cfeab76ea82c.png)

The writing for the bitfile is very slow. Thanks for the support.

**Comment by trabucayre** [comment]
JTAG interface is quite unstable in some case :-(
Never tested with a VM nor with windows.
For time to write: SPI flash is accessed with a bitbanging mode and can't be really fast.

Great to see everything is now working!
