### ISSUE TITLE
ModuleNotFoundError: No module named 'litex'

### ISSUE THREAD

**Issue by Peng-Hongxi** [litex-hub/litex-boards#527]
riscv@riscv-virtual-machine:~/python-litex/litex-boards/litex_boards/targets$ python3 sipeed_tang_nano_20k.py
Traceback (most recent call last):
  File "/home/riscv/python-litex/litex-boards/litex_boards/targets/sipeed_tang_nano_20k.py", line 13, in <module>
    from litex.gen import *
ModuleNotFoundError: No module named 'litex'

**Comment by enjoy-digital** [comment]
The issue is related to LiteX installation, please make sure to follow https://github.com/enjoy-digital/litex/wiki/Installation.
