### ISSUE TITLE
zedboard can't boot up correctly

### ISSUE THREAD

**Issue by phillippZZ** [litex-hub/litex-boards#594]
Hi, everyone.

I built a naxriscv bitstream and loaded it to zedboard. When I used the default linux image and other configuration files in a sdcard, I observed something on my monitor and the board had a few indicators powered on. 
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=2586272499896380209 skey=@crypt_9cc2dc5a_afe92e7d3620388879d113bf115e668e mmweb_appid=wx_webfilehelper](https://github.com/litex-hub/litex-boards/assets/171099706/f256f747-fbde-41a6-80ae-dcc7c218ebe4)
But when I put into the sdcard with files downloaded from "https://github.com/litex-hub/linux-on-litex-vexriscv/files/8331338/linux_2022_03_23.zip", the board only has power indicator lighting. I can't see anything on monitor or data transfered via uart on PuTTY

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=320211357029802481 skey=@crypt_9cc2dc5a_afe92e7d3620388879d113bf115e668e mmweb_appid=wx_webfilehelper](https://github.com/litex-hub/litex-boards/assets/171099706/f0dd9dc9-015e-41c9-83e2-9b57d145f6fd)

Is it because the image files don't use uart or I did something wrong?

**Comment by trabucayre** [comment]
I suppose the first image used was a stock firmaware for digilent? If true: it uses the PS (processor) and the PL(FPGA) is dedicated to extends features (VGA/HMDI).
With the second image from linux-on-vexriscv, PS part isn't used but SDCARD, UART, SDRAM and ethernet aren't available from PL. There is PR to access PS resources from PL but we have to review/merge it before.
So If you have to add PMOD extensions for SDCARD/UART/... and to modify the target accordingly.

**Comment by phillippZZ** [comment]
Thank you very much.
Some of the concepts are new to me, I'll have some research and test for now.

**Comment by phillippZZ** [comment]
hi, @trabucayre

I added the following code to _io in "litex_boards/platforms/digilent_zedboard.py":
>("serial", 0,
    Subsignal("tx", Pins("D11")),  # MIO[48] for TX
    Subsignal("rx", Pins("C14")),  # MIO[49] for RX
    IOStandard("LVCMOS33")         # Assuming 3.3V logic levels
),

The ID of the pins come from "https://digilent.com/reference/_media/zedboard:zedboard_ug.pdf" as shown in the attached image.
<img width="777" alt="image" src="https://github.com/litex-hub/litex-boards/assets/171099706/bba9d547-9f1e-4894-838e-b9e74af96c0e">


Then I got the following error from compiling:
>ERROR: [DRC UCIO-1] Unconstrained Logical Port: 2 out of 11 logical ports have no user assigned specific location constraint (LOC). This may cause I/O contention or incompatibility with the board power or connectivity affecting performance, signal integrity or in extreme cases cause damage to the device or the components to which it is connected. To correct this violation, specify all pin locations. This design will fail to generate a bitstream unless all logical ports have a user specified site LOC constraint defined.  To allow bitstream creation with unspecified pin locations (not recommended), use this command: set_property SEVERITY {Warning} [get_drc_checks UCIO-1].  NOTE: When using the Vivado Runs infrastructure (e.g. launch_runs Tcl command), add this command to a .tcl file and add that file as a pre-hook for write_bitstream step for the implementation run.  Problem ports: serial_rx, and serial_tx.

**Comment by trabucayre** [comment]
*MIO* pins are pins dedicated for PS, and not available from PL.
To have an UART you have to uses a PMOD extension (warning one of them is connected to the PS).
In fact, without the PR mentioned zedboard (with only the PL) has not enough BRAM to be able to run GNU/Linux OS.

**Comment by phillippZZ** [comment]
May I ask is it possible to connect PL to the UART of PS via some type of PMOD extension? Does it mean I have to write some code to build communication between PL and PS?
Or is it better to connect PL to an external UART via PMOD extension?

**Comment by trabucayre** [comment]
Yes, currently the best way is to have an external UART interface connected to a PMOD. Again there is work to allows PL to access to PS controller (and consequently to be able to use UART interface without external peripherals, but we have to review/test see how to have a easiest solution.
