### ISSUE TITLE
Titanium Ti375 C529 support

### ISSUE THREAD

**Issue by Dolu1990** [litex-hub/litex-boards#605]
Hi,

This is just to notify that i'm working on adding support for this dev kit : https://www.efinixinc.com/products-devkits-titaniumti375c529.html

Let's me know if you have done any related work previously ^^

**Comment by Dolu1990** [comment]
Got the uart / sdcard / usb host / debian to work.

**Comment by enjoy-digital** [comment]
Nice, thanks for sharing @Dolu1990! Not sure anyone started adding LiteX-Boards support to it.

**Comment by Dolu1990** [comment]
WIP : https://github.com/Dolu1990/litex-boards/tree/ti375_c529

Also got HDMI to work (https://www.digikey.fr/fr/products/detail/efinix-inc/EFX-HDMI/17084519)

**Comment by enjoy-digital** [comment]
Great!

**Comment by enjoy-digital** [comment]
Done with https://github.com/litex-hub/litex-boards/pull/610, thanks @Dolu1990!

**Comment by enjoy-digital** [comment]
@Dolu1990: You different PR have been merged, would you mind doing a test with upstream repos? (I also ordered a Ti375 to also be able to do some tests but the board is not yet there).

**Comment by Dolu1990** [comment]
@enjoy-digital Just tried with litex + litex-boards repository.
Seems all good, constraints look good and it does run debian at 200 Mhz ^^

Thanks !

**Comment by enjoy-digital** [comment]
Great, thanks for the feedback! We can probably close this issue since completed.

**Comment by Dolu1990** [comment]
For reference, here is the set of parameters for the incoming orconf demo running debian : 

--cpu-type=vexiiriscv --cpu-variant=debian --with-jtag-tap --with-sdcard --with-coherent-dma --with-ohci --vexii-video "name=video" --vexii-args="--fetch-l1-hardware-prefetch=nl --fetch-l1-refill-count=2 --fetch-l1-mem-data-width-min=128 --lsu-l1-mem-data-width-min=128 --lsu-software-prefetch --lsu-hardware-prefetch rpt --performance-counters 9 --lsu-l1-store-buffer-ops=32 --lsu-l1-refill-count 4 --lsu-l1-writeback-count 4 --lsu-l1-store-buffer-slots=4  --relaxed-div" --l2-bytes=524288 --sys-clk-freq 100000000 --cpu-clk-freq 200000000 --with-cpu-clk --bus-standard axi-lite --cpu-count=4

**Comment by enjoy-digital** [comment]
Thanks, indeed useful to save it somewhere :)
